controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

leapt_froala_editor:
    resource: '@LeaptFroalaEditorBundle/Resources/config/routing.php'
    prefix:   /froalaeditor
